# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define jobs to be invoked later in a workflow.
jobs:
  build-and-push:
    # Specify the execution environment using a Python 3.9 Docker image.
    docker:
      - image: cimg/python:3.9
    steps:
      # Checkout the code from the repository.
      - checkout

      # Install Python dependencies (if any).
      - run:
          name: Install Python dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r project-2048/2048-codes/requirements.txt  # If you have a requirements.txt file

      # Run the Python application (optional, if needed for testing or setup).
      - run:
          name: Run Python application
          command: python project-2048/2048-codes/app.py

      # Login to Docker Hub.
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Build Docker image.
      - run:
          name: Build Docker image
          command: |
            docker build -t vishaldock7/2048-game:latest .

      # Push Docker image to Docker Hub.
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push vishaldock7/2048-game:latest

# Orchestrate jobs using workflows.
workflows:
  build-and-push-workflow:  # Name of the workflow.
    jobs:
      - build-and-push  # Run the `build-and-push` job.
