version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /mypythonapp/docker/username
    DOCKER_REGISTRY_PASSWORD: /mypythonapp/docker/password
    DOCKER_REGISTRY_URL: /mypythonapp/docker/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r project-2048/2048-codes/requirements.txt
      - echo "Logging into the Docker..."
      - docker login $DOCKER_REGISTRY_URL --username $DOCKER_REGISTRY_USERNAME --password $DOCKER_REGISTRY_PASSWORD
  build:
    commands:
      - echo "Running tests..."
      - cd project-2048/2048-codes/
      - echo "Building Docker image..."
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/2048-app-image:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/2048-app-image:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../2048-codes

